version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: login-from-address-app
