# config/logging_config.yaml
version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR  # ← Теперь только ошибки будут в консоли
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG  # ← Полные логи пишем в файл
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

root:
  level: DEBUG
  handlers:
    - console
    - file